### ISSUE TITLE
Fatal error when trying to update: Pull from Salesforce > Run Schedule Every (wp-admin)

### ISSUE THREAD

**Issue by eli-antebi** [MinnPost/object-sync-for-salesforce#507] opened 2022-11-24 08:43 UTC
Environment: WP 6.1.1, ACF 5.12.2, PHP 8.1.6

To Reproduce: Settings > Salesforce > Scheduling > Change value in [Run Schedule Every] to "5" and A[Time Unit] to "Minutes"

Error:

Fatal error: Uncaught TypeError: DateTime::__construct(): Argument #1 ($datetime) must be of type string, array given in D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\functions.php:336 Stack trace: #0 D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\functions.php(336): DateTime->__construct(Array, Object(DateTimeZone)) #1 D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(114): as_get_datetime_object(Array) #2 D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(149): ActionScheduler_ActionFactory->single_unique('object_sync_for...', false, Array, 1669279306, 'salesforce_pull...') #3 D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\functions.php(59): ActionScheduler_ActionFactory->recurring_unique('object_sync_for...', Array, 1669279306, 0, 'salesforce_pull...', false) #4 D:\______________\wp-content\plugins\object-sync-for-salesforce\classes\class-object-sync-sf-queue.php(215): as_schedule_recurring_action(1669279306, 0, 'object_sync_for...', Array, 'salesforce_pull...') #5 D:\______________\wp-content\plugins\object-sync-for-salesforce\classes\class-object-sync-sf-admin.php(446): Object_Sync_Sf_Queue->schedule_recurring(1669279306, 0, 'object_sync_for...', Array, 'salesforce_pull...') #6 D:\______________\wp-content\plugins\object-sync-for-salesforce\classes\class-object-sync-sf-admin.php(399): Object_Sync_Sf_Admin->set_action_schedule('salesforce_pull', 'salesforce_pull...') #7 D:\______________\wp-includes\class-wp-hook.php(308): Object_Sync_Sf_Admin->initial_action_schedule('5', '0', 'object_sync_for...') #8 D:\______________\wp-includes\plugin.php(205): WP_Hook->apply_filters('5', Array) #9 D:\______________\wp-includes\option.php(463): apply_filters('pre_update_opti...', '5', '0', 'object_sync_for...') #10 D:\______________\wp-admin\options.php(322): update_option('object_sync_for...', '5') #11 {main} thrown in D:\______________\wp-content\plugins\object-sync-for-salesforce\vendor\woocommerce\action-scheduler\functions.php on line 336

**Comment by jonathanstegall** [comment] 2022-11-24 13:32
Duplicate of #504.

**Closed** 2022-11-24 13:36 UTC
Labels: duplicate

**Comment by jonathanstegall** [comment] 2022-11-24 13:38
To be clear, you can try the patch at https://github.com/woocommerce/action-scheduler/pull/883 (and possibly encourage them to merge it!)
